# Generated by Django 5.0.3 on 2024-05-17 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='time_out',
            field=models.CharField(max_length=150),
        ),
    ]
