# Generated by Django 5.0.3 on 2024-05-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_baby_time_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doll_name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DollSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price_of_doll', models.IntegerField()),
                ('babyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.baby')),
                ('doll_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.doll')),
            ],
        ),
        migrations.CreateModel(
            name='AssignProcurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('babyname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.baby')),
                ('name_of_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.procurement')),
            ],
        ),
    ]
